// src/pages/dashboard/profile.vue
<template>
    <div class="min-h-screen bg-gray-50 flex">
        <!-- Sidebar -->
        <Sidebar :user="user" />

        <!-- Main Content -->
        <div class="flex-1 flex flex-col">
            <!-- Top Navigation -->
            <header class="bg-white border-b border-gray-200 px-4 sm:px-6 py-4">
                <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between space-y-3 sm:space-y-0">
                    <div class="text-center sm:text-left">
                        <h1 class="text-xl sm:text-2xl font-bold text-gray-900">Edit Profile</h1>
                        <p class="text-sm text-gray-600">Update your personal information</p>
                    </div>

                    <!-- Save Button -->
                    <div class="flex justify-center sm:justify-end">
                        <button @click="saveProfile" :disabled="loading || uploading"
                            class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors w-full sm:w-auto">
                            <span v-if="loading">Saving...</span>
                            <span v-else-if="uploading">Uploading...</span>
                            <span v-else>Save Changes</span>
                        </button>
                    </div>
                </div>
            </header>

            <!-- Main Content Area -->
            <main class="flex-1 p-4 sm:p-6 flex flex-col">
                <div class="max-w-4xl mx-auto flex-1 flex flex-col">
                    <div class="bg-white rounded-lg shadow-sm border border-gray-200">
                        <!-- Profile Picture Section -->
                        <div class="p-4 sm:p-8 border-b border-gray-200">
                            <h2 class="text-lg font-semibold text-gray-900 mb-4 sm:mb-6">Profile Picture</h2>
                            <div class="flex flex-col sm:flex-row sm:items-center space-y-4 sm:space-y-0 sm:space-x-6">
                                <div class="relative flex justify-center sm:justify-start">
                                    <div v-if="profileImage"
                                        class="w-20 h-20 sm:w-24 sm:h-24 rounded-full border-4 border-gray-200 overflow-hidden relative">
                                        <img :src="profileImage" alt="Profile Picture"
                                            class="w-full h-full object-cover" />
                                    </div>
                                    <div v-else
                                        class="w-20 h-20 sm:w-24 sm:h-24 rounded-full border-4 border-gray-200 bg-blue-100 flex items-center justify-center relative">
                                        <span class="text-blue-600 font-bold text-xl sm:text-2xl">{{ userInitials
                                            }}</span>
                                    </div>
                                </div>
                                <div class="flex-1 text-center sm:text-left">
                                    <h3 class="text-sm font-medium text-gray-900 mb-2">Update your profile picture</h3>
                                    <p class="text-sm text-gray-600 mb-4">Upload a new image to personalize your profile
                                    </p>

                                    <!-- Upload Progress -->
                                    <div v-if="uploading" class="mb-4">
                                        <div class="flex items-center space-x-2">
                                            <div class="flex-1 bg-gray-200 rounded-full h-2">
                                                <div class="bg-blue-600 h-2 rounded-full transition-all duration-300"
                                                    :style="{ width: `${uploadProgress}%` }"></div>
                                            </div>
                                            <span class="text-sm text-gray-600">{{ uploadProgress }}%</span>
                                        </div>
                                    </div>

                                    <input ref="fileInput" type="file" accept="image/*" @change="handleImageUpload"
                                        class="hidden" />
                                    <button @click="triggerFileInput" :disabled="uploading"
                                        class="bg-gray-100 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-200 transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed w-full sm:w-auto">
                                        {{ uploading ? 'Uploading...' : 'Choose Image' }}
                                    </button>
                                </div>
                            </div>
                        </div>

                        <!-- Personal Information Section -->
                        <div class="p-8 border-b border-gray-200">
                            <!-- Error Message -->
                            <div v-if="error" class="mb-6 bg-red-50 border border-red-200 rounded-lg p-3">
                                <p class="text-sm text-red-600">{{ error }}</p>
                            </div>

                            <!-- Success Message -->
                            <div v-if="success" class="mb-6 bg-green-50 border border-green-200 rounded-lg p-3">
                                <p class="text-sm text-green-600">{{ success }}</p>
                            </div>

                            <h2 class="text-lg font-semibold text-gray-900 mb-6">Personal Information</h2>
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div>
                                    <label for="name" class="block text-sm font-medium text-gray-700 mb-2">Full
                                        Name</label>
                                    <input id="name" v-model="form.name" type="text" required
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                                </div>
                                <div>
                                    <label for="email" class="block text-sm font-medium text-gray-700 mb-2">Email
                                        Address</label>
                                    <input id="email" v-model="form.email" type="email" readonly required
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-gray-50 text-gray-500 cursor-not-allowed" />
                                </div>
                                <div>
                                    <label for="phone" class="block text-sm font-medium text-gray-700 mb-2">Phone
                                        Number</label>
                                    <input id="phone" v-model="form.phone" type="tel" readonly required
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-gray-50 text-gray-500 cursor-not-allowed" />
                                </div>
                                <div>
                                    <label for="dob" class="block text-sm font-medium text-gray-700 mb-2">Date of
                                        Birth</label>
                                    <input id="dob" v-model="form.dob" type="date" required
                                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                                </div>
                            </div>
                        </div>

                        <!-- Account Information Section -->
                        <div class="p-8">
                            <h2 class="text-lg font-semibold text-gray-900 mb-6">Account Information</h2>
                            <div class="space-y-4">
                                <div class="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                                    <div>
                                        <h3 class="text-sm font-medium text-gray-900">Account Status</h3>
                                        <p class="text-sm text-gray-600">{{ user?.isPro ? 'Pro Account' : 'Free Account'
                                            }}</p>
                                    </div>
                                    <span
                                        :class="user?.isPro ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'"
                                        class="px-2 py-1 text-xs font-medium rounded-full">
                                        {{ user?.isPro ? 'Pro' : 'Free' }}
                                    </span>
                                </div>
                                <div class="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                                    <div>
                                        <h3 class="text-sm font-medium text-gray-900">Member Since</h3>
                                        <p class="text-sm text-gray-600">{{ memberSince }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Footer -->
                <div class="mt-auto">
                    <Footer />
                </div>
            </main>
        </div>
    </div>
</template>

<script setup>
import { ref, onMounted, computed } from 'vue'

import { useAuthStore } from '~/stores/auth'
import { useImageUpload } from '~/composables/useImageUpload'
import Sidebar from '@/components/dashboard/Sidebar.vue'
import Footer from '@/components/Footer.vue'


const authStore = useAuthStore()
const { uploadImage, validateImage, compressImage, uploading, uploadProgress } = useImageUpload()

const loading = ref(false)
const error = ref('')
const success = ref('')
const fileInput = ref(null)
const profileImage = ref('')
const selectedFile = ref(null)

const form = ref({
    name: '',
    email: '',
    phone: '',
    dob: ''
})

const triggerFileInput = () => {
    fileInput.value?.click()
}

const handleImageUpload = async (event) => {
    const file = event.target.files[0]
    if (!file) return

    // Validate file
    if (!validateImage(file)) {
        error.value = 'Please select a valid image file (JPEG, PNG, WebP) under 5MB'
        return
    }

    try {
        // Show preview immediately
        const reader = new FileReader()
        reader.onload = (e) => {
            profileImage.value = e.target.result
        }
        reader.readAsDataURL(file)

        // Compress and upload image
        const compressedFile = await compressImage(file)
        selectedFile.value = compressedFile

        // Upload to Firebase
        const downloadURL = await uploadImage(compressedFile, 'profile-images')
        profileImage.value = downloadURL

        success.value = 'Profile picture uploaded successfully!'
        setTimeout(() => {
            success.value = ''
        }, 3000)

    } catch (err) {
        console.error('Image upload error:', err)
        error.value = 'Failed to upload image. Please try again.'
        // Reset preview
        profileImage.value = user.value?.profileImage || ''
    }
}

// Computed
const user = computed(() => authStore.getUser)

const userInitials = computed(() => {
    const name = form.value.name || ''
    return name.split(' ').map(n => n.charAt(0)).join('').toUpperCase().slice(0, 2)
})

const memberSince = computed(() => {
    if (!user.value?.id) return 'N/A'
    // This would typically come from the user data, but for now we'll show a placeholder
    return 'Recently joined'
})

// Format date for display (convert from DD/MM/YYYY to YYYY-MM-DD)
const formatDateForInput = (dateString) => {
    if (!dateString) return ''
    const parts = dateString.split('/')
    if (parts.length === 3) {
        return `${parts[2]}-${parts[1]}-${parts[0]}`
    }
    return dateString
}

// Format date for API (convert from YYYY-MM-DD to DD/MM/YYYY)
const formatDateForAPI = (dateString) => {
    if (!dateString) return ''
    const date = new Date(dateString)
    const day = String(date.getDate()).padStart(2, '0')
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const year = date.getFullYear()
    return `${day}/${month}/${year}`
}

const saveProfile = async () => {
    loading.value = true
    error.value = ''
    success.value = ''

    try {
        const profileData = {
            name: form.value.name,
            email: form.value.email, // Include email since API requires it
            dob: formatDateForAPI(form.value.dob),
            profileImage: profileImage.value
        };

        const result = await authStore.updateProfile(profileData)

        if (result.success) {
            success.value = 'Profile updated successfully!'
            setTimeout(() => {
                success.value = ''
            }, 3000)
        } else {
            error.value = result.error || 'Profile update failed'
        }
    } catch (err) {
        console.error('Error updating profile:', err)
        error.value = 'An unexpected error occurred'
    } finally {
        loading.value = false
    }
}

onMounted(async () => {
    // Load existing user data from auth store
    const currentUser = authStore.getUser
    if (currentUser) {
        form.value = {
            name: currentUser.name || '',
            email: currentUser.email || '',
            phone: currentUser.phone || '',
            dob: formatDateForInput(currentUser.dob || '')
        }
        profileImage.value = currentUser.profileImage || ''
    } else {
        // If no user data, try to fetch it
        await authStore.fetchUser()
        const fetchedUser = authStore.getUser
        if (fetchedUser) {
            form.value = {
                name: fetchedUser.name || '',
                email: fetchedUser.email || '',
                phone: fetchedUser.phone || '',
                dob: formatDateForInput(fetchedUser.dob || '')
            }
            profileImage.value = fetchedUser.profileImage || ''
        }
    }
})

// Set page title
useHead({
    title: 'Edit Profile - QWESI AI'
})
</script>

// app/(public)/profile/page.jsx
'use client'
import { useEffect, useState } from 'react'
import Loading from '@/components/Loading'
import { readAuth, validateStoredToken, persistAuth, authFetch } from '@/lib/auth'
import { API_ROUTES } from '@/lib/apiRoutes'
import toast from 'react-hot-toast'
import { User, Mail, Phone, Calendar, ShieldAlert, Briefcase, MapPin } from 'lucide-react'

const API_BASE_URL = 'https://dark-caldron-448714-u5.uc.r.appspot.com/api'

export default function ProfilePage() {
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const [editMode, setEditMode] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ name: '', email: '', dob: '' })
  const [formError, setFormError] = useState('')

  useEffect(() => {
    const init = async () => {
      setLoading(true)
      setError('')
      try {
        // Ensure token is still valid, will auto-clear on invalid
        await validateStoredToken()
        const auth = readAuth()
        const token = auth?.token

        if (!token) {
          setError('Please login to view your profile.')
          setUser(null)
          return
        }

        // Fetch latest user details from backend
        const response = await authFetch(`${API_BASE_URL}/dashboard/qwesi/personal?id=${auth?.user?.id}`)
        if (response.ok) {
            const data = await response.json()
            if (data.success) {
                setUser(data.data.profile)
            } else {
                setUser(auth?.user || null)
            }
        } else {
            setUser(auth?.user || null)
        }
      } catch (e) {
        setError(e?.message || 'Failed to load profile.')
        setUser(null)
      } finally {
        setLoading(false)
      }
    }
    init()
  }, [])

  useEffect(() => {
    if (user) {
      setForm({
        name: user.name || '',
        email: user.email || '',
        dob: user.dob || user.dateOfBirth || ''
      })
    }
  }, [user])

  const handleSave = async (e) => {
    e.preventDefault()
    setSaving(true)
    setFormError('')
    try {
      // Basic client validations similar to backend
      if (!form.name || !form.email || !form.dob) {
        throw new Error('Please fill all fields')
      }
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
      if (!emailRegex.test(form.email)) {
        throw new Error('Invalid email format')
      }
      const dateRegex = /^\d{2}\/\d{2}\/\d{4}$/
      if (!dateRegex.test(form.dob)) {
        throw new Error('Date must be in DD/MM/YYYY format')
      }

      const res = await authFetch(API_ROUTES.EDIT_PROFILE, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: form.name, email: form.email, dob: form.dob }),
      })

      let data = null
      try { data = await res.json() } catch {}

      const updatedUser = (data && (data.user || data.data)) ? (data.user || data.data) : { ...user, ...form }
      setUser(updatedUser)

      // persist updated user with existing token
      const auth = readAuth()
      const token = auth?.token || null
      try { persistAuth({ user: updatedUser, token }) } catch {}

      toast.success((data && data.message) ? data.message : 'Profile updated successfully')
      setEditMode(false)
    } catch (err) {
      setFormError(err?.message || 'Failed to update profile')
    } finally {
      setSaving(false)
    }
  }

  if (loading) return <Loading />

  if (!user) {
    return (
      <div className="max-w-3xl mx-auto p-6">
        <div className="bg-white border border-slate-200 rounded-xl p-8 text-center">
          <ShieldAlert className="w-10 h-10 text-orange-600 mx-auto mb-3" />
          <h1 className="text-xl font-semibold text-slate-800 mb-2">Authentication required</h1>
          <p className="text-slate-600 mb-6">{error || 'Please login to access your profile.'}</p>
          <a href="#" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">Go to login</a>
        </div>
      </div>
    )
  }

  return (
    <div className="max-w-3xl mx-auto p-6">
      <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden">
        <div className="bg-gradient-to-r from-blue-600 to-indigo-600 p-6 text-white">
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-full bg-white/20 flex items-center justify-center text-white text-xl font-bold">
                {user?.name?.charAt(0)?.toUpperCase() || 'U'}
              </div>
              <div>
                <h1 className="text-2xl font-bold">{user?.name || 'Your Profile'}</h1>
                <p className="text-sm text-white/80">Manage your account information</p>
              </div>
            </div>
            <button
              onClick={() => { setEditMode(!editMode); setFormError('') }}
              className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-sm font-medium"
            >
              {editMode ? 'Cancel' : 'Edit Profile'}
            </button>
          </div>
        </div>

        <div className="p-6 space-y-5">
          {editMode ? (
            <form onSubmit={handleSave} className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Full name</label>
                  <input
                    className="w-full px-3 py-2 border rounded-lg"
                    value={form.name}
                    onChange={(e) => setForm({ ...form, name: e.target.value })}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
                  <input
                    type="email"
                    className="w-full px-3 py-2 border rounded-lg"
                    value={form.email}
                    onChange={(e) => setForm({ ...form, email: e.target.value })}
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Date of Birth</label>
                <input
                  placeholder="DD/MM/YYYY"
                  className="w-full px-3 py-2 border rounded-lg"
                  value={form.dob}
                  onChange={(e) => setForm({ ...form, dob: e.target.value })}
                />
              </div>
              {formError && <div className="text-sm text-red-600">{formError}</div>}
              <div className="flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => { setEditMode(false); setFormError('') }}
                  className="px-4 py-2 border rounded-lg"
                  disabled={saving}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={saving}
                  className="px-4 py-2 bg-blue-600 text-white rounded-lg"
                >
                  {saving ? 'Saving...' : 'Save Changes'}
                </button>
              </div>
            </form>
          ) : (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <InfoCard icon={User} label="Full name" value={user?.name || 'N/A'} />
                <InfoCard icon={Mail} label="Email" value={user?.email || 'N/A'} />
                <InfoCard icon={Phone} label="Phone" value={user?.phone || user?.mobile || 'N/A'} />
                <InfoCard icon={Calendar} label="Date of Birth" value={user?.dob || user?.dateOfBirth || 'N/A'} />
                <InfoCard icon={Briefcase} label="User Type" value={user?.userType || 'N/A'} />
                <InfoCard icon={MapPin} label="Country" value={user?.country || 'N/A'} />
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

function InfoCard({ icon: Icon, label, value }) {
  return (
    <div className="border border-slate-200 rounded-xl p-4 bg-white flex items-center gap-3">
      <div className="p-2 rounded-lg bg-blue-50 text-blue-700"><Icon className="w-5 h-5" /></div>
      <div>
        <div className="text-xs text-slate-500">{label}</div>
        <div className="text-sm font-medium text-slate-800">{value}</div>
      </div>
    </div>
  )
}
